### ISSUE TITLE
"no directive is matched on attribute rxLet" - Angular 10

### ISSUE THREAD

**Issue by matze1234** [rx-angular/rx-angular#201]
I'm trying to use the *rxLet directive, but within template it says "**no directive is matched on attribute rxLet**"

I included TemplateModule. I tried with a fresh Angular 10 application.
Am i missing something?

**Comment by BioPhoton** [comment]
related to #203

**Comment by muuvmuuv** [comment]
I have fixed it by compiling `template` myself and replacing it in my projects node_modules. So the GitHub master branch seems to include the fix.

**Comment by BioPhoton** [comment]
Atm we only face that issue in vscode.
what ide are you using?

**Comment by dallastjames** [comment]
Just updated to the latest alpha.6 and still seeing this in VSCode. Aside from the error in the IDE, everything compiles and runs without issue.

**Comment by Karnaukhov-kh** [comment]
Hi @dallastjames, @matze1234. 

This is an [issue](https://github.com/angular/vscode-ng-language-service/issues/645) with Angular language service for VSCode.
You can read more details in [this comment](https://github.com/angular/vscode-ng-language-service/issues/645#issuecomment-648032102). They are working on it and the latest status can be found [here](https://github.com/angular/vscode-ng-language-service/issues/335). As for today, their plan is to release beta version with fix in November.

If we manage to find some workaround for this we will provide it here & in the docs.

**Comment by BioPhoton** [comment]
@Karnaukhov-kh I assume it works with the latest release of Angualr?

**Comment by Karnaukhov-kh** [comment]
Not really connected to angular releases, it should work in the 11.* Language service with ivy.

Status can be checked here: https://github.com/angular/vscode-ng-language-service/releases

**Comment by muuvmuuv** [comment]
I do get this now in the browser too: 

```
NG0303: Can't bind to 'rxLetError' since it isn't a known property of 'ng-container'.
```

```json
    "@angular/animations": "^11.0.8",
    "@angular/cdk": "^11.0.3",
    "@angular/common": "^11.0.8",
    "@angular/compiler": "^11.0.8",
    "@angular/core": "^11.0.8",
    "@angular/forms": "^11.0.8",
    "@angular/material": "^11.0.3",
    "@angular/platform-browser": "^11.0.8",
    "@angular/platform-browser-dynamic": "^11.0.8",
    "@angular/router": "^11.0.8",
    "@angular/service-worker": "^11.0.8",
    "@rx-angular/state": "^1.4.3",
    "@rx-angular/template": "^1.0.0-beta.4"
```

**Comment by tayambamwanza** [comment]
This might have been fixed with experimental ivy language service, I'm not seeing this error anymore, can anyone else confirm?

**Comment by hoebbelsB** [comment]
@tayambamwanza yes, this got fixed here: https://github.com/rx-angular/rx-angular/pull/553 I will close this issue :) thx for reporting back!

**Comment by montella1507** [comment]
Latest NX workspace, WebStorm. Same problem.

`"dependencies": {
    "@angular/animations": "12.0.0",
    "@angular/common": "12.0.0",
    "@angular/compiler": "12.0.0",
    "@angular/core": "12.0.0",
    "@angular/forms": "12.0.0",
    "@angular/platform-browser": "12.0.0",
    "@angular/platform-browser-dynamic": "12.0.0",
    "@angular/router": "12.0.0",
    "@capacitor/core": "2.4.5",
    "@ionic-native/core": "5.30.0",
    "@ionic-native/splash-screen": "5.30.0",
    "@ionic-native/status-bar": "5.30.0",
    "@ionic/angular": "5.5.2",
    "@rx-angular/cdk": "^1.0.0-alpha.8",
    "@rx-angular/state": "^1.4.3",
    "@rx-angular/template": "^1.0.0-beta.25",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.0.0",
    "@angular/compiler-cli": "12.0.0",
    "@angular/language-service": "12.0.0",
    "@capacitor/android": "2.4.5",
    "@capacitor/ios": "2.4.5",
    "@nrwl/angular": "12.3.1",
    "@nrwl/cli": "12.3.1",
    "@nrwl/cypress": "12.3.1",
    "@nrwl/eslint-plugin-nx": "^12.3.1",
    "@nrwl/nx-cloud": "12.1.1",
    "@nrwl/tao": "12.3.1",
    "@nrwl/workspace": "12.3.1",
    "@nxtend/capacitor": "11.0.0",
    "@nxtend/ionic-angular": "11.0.0",
    "@types/jasmine": "~3.5.0",
    "@types/node": "14.14.33",
    "@types/office-js": "^1.0.108",
    "@types/office-runtime": "^1.0.14",
    "@typescript-eslint/eslint-plugin": "^4.23.0",
    "@typescript-eslint/parser": "^4.23.0",
    "codelyzer": "^6.0.0",
    "cypress": "^5.5.0",
    "dotenv": "8.2.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "^8.3.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "office-addin-manifest": "^1.5.13",
    "prettier": "2.2.1",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.0",
    "typescript": "4.2.4"
  }`
